exporters:
  debug:
    verbosity: basic

  splunk_hec/traces:
    token: ${env:SPLUNK_HEC_TOKEN}
    endpoint: ${env:SPLUNK_HEC_ENDPOINT}
    source: "app"
    sourcetype: "traces"
    index: "direct_access_otel_traces"
  splunk_hec/metrics:
    token: ${env:SPLUNK_HEC_TOKEN}
    endpoint: ${env:SPLUNK_HEC_ENDPOINT}
    source: "app"
    sourcetype: "metrics"
    index: "direct_access_otel_metrics"
  splunk_hec/logs:
    token: ${env:SPLUNK_HEC_TOKEN}
    endpoint: ${env:SPLUNK_HEC_ENDPOINT}
    source: "app"
    sourcetype: "logs"
    index: "direct_access_otel_logs"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_GRPC}
      http:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_HTTP}
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
  httpcheck/frontendproxy:
    targets:
      - endpoint: http://frontendproxy:${env:ENVOY_PORT}
  hostmetrics:
    collection_interval: 10s
    root_path: /hostfs
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
          system.cpu.logical.count:
            enabled: true
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      process:
        mute_process_exe_error: true
        mute_process_io_error: true
        mute_process_user_error: true
        metrics:
          process.threads:
            enabled: true
          process.open_file_descriptors:
            enabled: true
          process.memory.utilization:
            enabled: true
          process.disk.operations:
            enabled: true
      network:
      processes:
      load:
      disk:
      filesystem:
        exclude_mount_points:
          mount_points:
            - /dev/*
            - /proc/*
            - /sys/*
            - /run/k3s/containerd/*
            - /var/lib/docker/*
            - /var/lib/kubelet/*
            - /snap/*
          match_type: regexp
        exclude_fs_types:
          fs_types:
            - autofs
            - binfmt_misc
            - bpf
            - cgroup2
            - configfs
            - debugfs
            - devpts
            - devtmpfs
            - fusectl
            - hugetlbfs
            - iso9660
            - mqueue
            - nsfs
            - overlay
            - proc
            - procfs
            - pstore
            - rpc_pipefs
            - securityfs
            - selinuxfs
            - squashfs
            - sysfs
            - tracefs
          match_type: strict

processors:
  batch/aggs:
    send_batch_size: 16384 # 2x the default
    timeout: 10s
  batch:
  batch/metrics:
    # explicitly set send_batch_max_size to 0, as splitting metrics requests may cause version_conflict_engine_exception in TSDB
    send_batch_max_size: 0
    timeout: 1s
  resource/process:
    attributes:
      - key: process.executable.name
        action: delete
      - key: process.executable.path
        action: delete
  attributes/dataset:
    actions:
      - key: event.dataset
        from_attribute: data_stream.dataset
        action: upsert
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
      resource_attributes:
        host.name:
          enabled: true
        host.id:
          enabled: false
        host.arch:
          enabled: true
        host.ip:
          enabled: true
        host.mac:
          enabled: true
        host.cpu.vendor.id:
          enabled: true
        host.cpu.family:
          enabled: true
        host.cpu.model.id:
          enabled: true
        host.cpu.model.name:
          enabled: true
        host.cpu.stepping:
          enabled: true
        host.cpu.cache.l2.size:
          enabled: true
        os.description:
          enabled: true
        os.type:
          enabled: true
  transform:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          # could be removed when https://github.com/vercel/next.js/pull/64852 is fixed upstream
          - replace_pattern(name, "\\?.*", "")
          - replace_match(name, "GET /api/products/*", "GET /api/products/{productId}")
  
connectors:
  spanmetrics:

service:
  pipelines:
    logs:
      exporters:
        - debug
        - splunk_hec/logs
      processors:
        - batch
      receivers:
        - otlp
    metrics/infra/ecs:
      exporters:
        - splunk_hec/metrics
        - debug
      processors:
        - batch/metrics
        - resourcedetection/system
        - attributes/dataset
        - resource/process
      receivers:
        - hostmetrics
    metrics/infra/otel:
      exporters:
        - splunk_hec/metrics
        - debug
      processors:
        - batch/metrics
        - resourcedetection/system
      receivers:
        - hostmetrics
    metrics:
      exporters:
        - splunk_hec/metrics
        - debug
      processors:
        - batch/metrics
      receivers:
        - httpcheck/frontendproxy
        - otlp
        - spanmetrics
    traces:
      exporters:
        - splunk_hec/traces
        - debug
        - spanmetrics
      processors:
        - transform
        - batch
      receivers:
        - otlp
